### ISSUE TITLE
Select all (CTRL+A) does not select all

### ISSUE THREAD

**Issue by Caroga** [fernandofig/jquery-formatcurrency#1]
Hi!

Currently implementing your library. I've noticed that when pressing CTRL+A inside a input field with the below configurations does not work. It selects the content, and then just goes back to the state it was before the key combo.

`$('[data-format-as-currency]').formatCurrency().formatCurrencyLive();`

I've been using Chrome, have not tested this in any other browser.

Could you take a look into this as this is a lot easier to erase/replace the input field's content?

Kind regards,
Caroga

**Comment by fernandofig** [comment]
Hi there!

Thanks for pointing that out. I've just pushed a commit (839e95238ca8d34ef9a36a22bf5e8ffd5321e245) that I believe should fix your issue - at least it does on my tests here. I've also changed the formatCurrencyLive method so that the element gets formatted when you call formatCurrencyLive on it, so now you can rewrite your code to just:

`$('[data-format-as-currency]').formatCurrencyLive();`

As for the fix for the issue you've reported, keep in mind you might still see some awkward behavior - CTRL+A does work now, but e.g. pressing CTRL+A, unfocusing the element then focusing it back will flick the selection back to unselected. That's something I couldn't figure out why it happens, and frankly doesn't seem like a big issue that would warrant wasting too much time on. This plugin is badly in need of a rewrite anyway, and I'm not even the original author, I've just added some enhancements.

Cheers,

Fernando

**Comment by Caroga** [comment]
Hi Fernando,

Thank you for this very quick response. 
I understand you are not the original author, therefore I'm even more grateful for your support on this issue.

I agree to your statement on the other behavior you described. When losing focus and returning back to the input field does not need to have the content selected as it was before. Pressing CTRL+A should be required.

I'll test it after my current feature, and will report back if successful. 

Cheers,
Caroga
